apiVersion: v1
kind: Secret
metadata:
  name: polaris-db
  namespace: polaris
  labels:
    app: polaris-db
type: Opaque
stringData:
  username: polaris
  password: polaris
  database: polaris
  jdbcUrl: jdbc:postgresql://polaris-db.polaris.svc.cluster.local:5432/polaris
