apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polaris-db
  namespace: polaris
  labels:
    app: polaris-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
