# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
  KUBE_CONTEXT: '{{env "KUBE_CONTEXT" | default "mini"}}'

env:
  KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list
    silent: true

  # --8<-- [start:init]
  init:
    desc: "Initialize local dev environment"
    cmds:
      - task: setup-node
      - task: setup-python
      - task: setup-pre-commit

  setup-node:
    desc: "Install Node dependencies"
    internal: true
    cmds:
      - npm clean-install --save-dev @commitlint/cli @commitlint/config-conventional

  setup-python:
    desc: "Install Python dependencies"
    internal: true
    cmds:
      - uv sync --locked --all-packages

  setup-pre-commit:
    desc: "Setup pre-commit hooks"
    internal: true
    cmds:
      - uv run pre-commit install
  # --8<-- [end:init]

  # --8<-- [start:checks]
  run-pre-commit-checks:
    desc: "Run pre commit hooks"
    cmds:
      - uv run pre-commit run --all-files --show-diff-on-failure
  # --8<-- [end:checks]

  # --8<-- [start:bootstrap-apps]
  bootstrap-apps:
    desc: "Bootstrap all K8s components in deployment order"
    cmds:
      - task: deploy-argocd
      - task: patch-argocd
      - task: deploy-cert-manager
      - task: deploy-keda
      - task: deploy-prometheus-operator
      - task: deploy-strimzi-operator
      - task: deploy-otel-operator
      - task: deploy-spark-operator
      - task: deploy-jaeger-thanos
      - task: deploy-jaeger-trino
      - task: deploy-kafka-cluster
      - task: deploy-minio
      - task: deploy-mysql
      - task: deploy-debezium-mysql-connector
      - task: deploy-iceberg-connector
      - task: deploy-trino
      - task: deploy-thanos

  deploy-argocd:
    desc: "Install ArgoCD"
    internal: true
    dir: 00-argocd
    cmds:
      - bash install.sh
      - bash validate.sh

  patch-argocd:
    desc: "Patch ArgoCD configmap"
    internal: true
    dir: 01-argocd-patch
    cmds:
      - bash install.sh

  deploy-cert-manager:
    desc: "Deploy cert-manager"
    internal: true
    dir: 10-cert-manager
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-keda:
    desc: "Deploy KEDA"
    internal: true
    dir: 10-keda
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-prometheus-operator:
    desc: "Deploy Prometheus Operator"
    internal: true
    dir: 10-prometheus
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-strimzi-operator:
    desc: "Deploy Strimzi Operator"
    internal: true
    dir: 10-strimzi-operator
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-otel-operator:
    desc: "Deploy OpenTelemetry Operator"
    internal: true
    dir: 11-otel-operator
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-spark-operator:
    desc: "Deploy Spark Operator"
    internal: true
    dir: 11-spark-operator
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-jaeger-thanos:
    desc: "Deploy Jaeger for Thanos"
    internal: true
    dir: 12-jaeger-thanos
    cmds:
      - bash install.sh

  deploy-jaeger-trino:
    desc: "Deploy Jaeger for Trino"
    internal: true
    dir: 12-jaeger-trino
    cmds:
      - bash install.sh

  deploy-kafka-cluster:
    desc: "Deploy Kafka cluster"
    internal: true
    dir: 20-kafka-cluster
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-minio:
    desc: "Deploy MinIO"
    internal: true
    dir: 20-minio
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-mysql:
    desc: "Deploy MySQL"
    internal: true
    dir: 20-mysql
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-debezium-mysql-connector:
    desc: "Deploy Debezium MySQL connector"
    internal: true
    dir: 21-kafka-debezium-mysql-connector
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-iceberg-connector:
    desc: "Deploy Iceberg sink connector"
    internal: true
    dir: 22-kafka-iceberg-connector
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-trino:
    desc: "Deploy Trino"
    internal: true
    dir: 23-trino
    cmds:
      - bash install.sh
      - bash validate.sh

  deploy-thanos:
    desc: "Deploy Thanos"
    internal: true
    dir: 30-thanos
    cmds:
      - bash install.sh
      - bash validate.sh
  # --8<-- [end:bootstrap-apps]

  # --8<-- [start:docs]
  serve-docs:
    desc: Serve docs locally
    cmds:
      - uv run mkdocs serve --livereload -a localhost:8591
