# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  bootstrap:
    desc: "Bootstrap all K8s apps (DEPLOY_METHOD: scripts|argocd)"
    requires:
      vars:
        - name: KUBE_CONTEXT
        - name: DEPLOY_METHOD
          enum: ["scripts", "argocd"]
    cmds:
      - task: bootstrap-by-{{.DEPLOY_METHOD}}
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"

  bootstrap-by-scripts:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 10-cert-manager/install.sh
      - bash 10-kube-prometheus/install.sh
      - bash 10-strimzi-operator/install.sh
      - bash 10-cert-manager/validate.sh
      - bash 10-kube-prometheus/validate.sh
      - bash 10-strimzi-operator/validate.sh
      - bash 11-keda/install.sh
      - bash 11-spark-operator/install.sh
      - bash 11-otel-operator/install.sh
      - bash 11-keda/validate.sh
      - bash 11-spark-operator/validate.sh
      - bash 11-otel-operator/validate.sh
      - bash 20-kafka-cluster/install.sh
      - bash 20-minio/install.sh
      - bash 20-mysql/install.sh
      - bash 20-jaeger-thanos/install.sh
      - bash 20-jaeger-trino/install.sh
      - bash 20-polaris-db/install.sh
      - bash 20-kafka-cluster/validate.sh
      - bash 20-minio/validate.sh
      - bash 20-mysql/validate.sh
      - bash 20-jaeger-thanos/validate.sh
      - bash 20-jaeger-trino/validate.sh
      - bash 20-polaris-db/validate.sh
      - bash 21-polaris/install.sh
      - bash 21-polaris/validate.sh
      - bash 21-kafka-debezium-mysql-connector/install.sh
      - bash 21-kafka-debezium-mysql-connector/validate.sh
      - bash 22-kafka-iceberg-connector/install.sh
      - bash 22-kafka-iceberg-connector/validate.sh
      - bash 23-trino/install.sh
      - bash 23-trino/validate.sh

  bootstrap-by-argocd:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 00-argocd/install.sh
      - bash 00-argocd/validate.sh
      - bash 01-argocd-health-checks/patch.sh
      - bash 02-argocd-apps/install.sh
      - bash 02-argocd-apps/validate.sh

  validate:
    desc: "Validate all K8s apps in parallel (KUBE_CONTEXT required)"
    requires:
      vars:
        - name: KUBE_CONTEXT
    deps:
      - task: validate-cert-manager
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-kube-prometheus
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-strimzi-operator
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-keda
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-spark-operator
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-otel-operator
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-kafka-cluster
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-minio
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-mysql
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-jaeger-thanos
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-jaeger-trino
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-kafka-debezium-mysql-connector
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-kafka-iceberg-connector
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-trino
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-polaris-db
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"
      - task: validate-polaris
        vars:
          KUBE_CONTEXT: "{{.KUBE_CONTEXT}}"

  validate-cert-manager:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 10-cert-manager/validate.sh

  validate-kube-prometheus:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 10-kube-prometheus/validate.sh

  validate-strimzi-operator:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 10-strimzi-operator/validate.sh

  validate-keda:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 11-keda/validate.sh

  validate-spark-operator:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 11-spark-operator/validate.sh

  validate-otel-operator:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 11-otel-operator/validate.sh

  validate-kafka-cluster:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-kafka-cluster/validate.sh

  validate-minio:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-minio/validate.sh

  validate-mysql:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-mysql/validate.sh

  validate-jaeger-thanos:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-jaeger-thanos/validate.sh

  validate-jaeger-trino:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-jaeger-trino/validate.sh

  validate-kafka-debezium-mysql-connector:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 21-kafka-debezium-mysql-connector/validate.sh

  validate-kafka-iceberg-connector:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 22-kafka-iceberg-connector/validate.sh

  validate-trino:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 23-trino/validate.sh

  validate-polaris-db:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 20-polaris-db/validate.sh

  validate-polaris:
    internal: true
    env:
      KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
    cmds:
      - bash 21-polaris/validate.sh
