# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  bootstrap:
    desc: "Bootstrap local colima VM + minikube cluster"
    requires:
      vars:
        - name: KUBE_CONTEXT
          enum:
            ref: .AVAILABLE_KUBE_CONTEXTS | splitLines | compact
    cmds:
      - task: bootstrap-colima
        vars:
          KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
      - task: bootstrap-minikube
        vars:
          KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'

  bootstrap-colima:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
    status:
      - colima status -p {{.KUBE_CONTEXT}} >/dev/null 2>&1
    cmds:
      - |
        colima start \
          --cpu 9 \
          --memory 28 \
          --disk 120 \
          --runtime docker \
          --profile {{.KUBE_CONTEXT}}

  bootstrap-minikube:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
    status:
      - minikube status -p {{.KUBE_CONTEXT}} >/dev/null 2>&1
    cmds:
      - |
        minikube start \
          --profile {{.KUBE_CONTEXT}} \
          --nodes 1 \
          --cpus 9 \
          --memory 26G \
          --disk-size 120G \
          --driver docker \
          --container-runtime docker \
          --kubernetes-version v1.33.2 \
          --addons registry --addons metrics-server \
          --insecure-registry "10.0.0.0/24" \
          --delete-on-failure
