# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  bootstrap:
    desc: "Bootstrap local colima VM + minikube cluster"
    requires:
      vars:
        - name: KUBE_CONTEXT
    vars:
      CPU: '{{.CPU | default 9}}'
      MEMORY: '{{.MEMORY | default 28}}'
      DISK_SIZE: '{{.DISK_SIZE | default 120}}'
      MINIKUBE_MEMORY: '{{sub (int .MEMORY) 2}}'
    cmds:
      - task: bootstrap-colima
        vars:
          KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
          CPU: '{{.CPU}}'
          MEMORY: '{{.MEMORY}}'
          DISK_SIZE: '{{.DISK_SIZE}}'
      - task: bootstrap-minikube
        vars:
          KUBE_CONTEXT: '{{.KUBE_CONTEXT}}'
          CPU: '{{.CPU}}'
          MEMORY: '{{.MINIKUBE_MEMORY}}'
          DISK_SIZE: '{{.DISK_SIZE}}'

  bootstrap-colima:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
        - name: CPU
        - name: MEMORY
        - name: DISK_SIZE
    status:
      - colima status -p {{.KUBE_CONTEXT}} >/dev/null 2>&1
    cmds:
      - |
        colima start \
          --cpu {{.CPU}} \
          --memory {{.MEMORY}} \
          --disk {{.DISK_SIZE}} \
          --runtime docker \
          --profile {{.KUBE_CONTEXT}}

  bootstrap-minikube:
    internal: true
    requires:
      vars:
        - name: KUBE_CONTEXT
        - name: CPU
        - name: MEMORY
        - name: DISK_SIZE
    status:
      - minikube status -p {{.KUBE_CONTEXT}} >/dev/null 2>&1
    cmds:
      - |
        minikube start \
          --profile {{.KUBE_CONTEXT}} \
          --nodes 1 \
          --cpus {{.CPU}} \
          --memory {{.MEMORY}}G \
          --disk-size {{.DISK_SIZE}}G \
          --driver docker \
          --container-runtime docker \
          --kubernetes-version v1.33.2 \
          --addons registry --addons metrics-server \
          --insecure-registry "10.0.0.0/24" \
          --delete-on-failure
