# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: "Initialize local dev environment"
    cmds:
      - task: install-node
      - task: install-python
      - task: install-pre-commit

  install-node:
    desc: "Install Node dependencies"
    internal: true
    cmds:
      - npm clean-install --save-dev @commitlint/cli @commitlint/config-conventional

  install-python:
    desc: "Install Python dependencies"
    internal: true
    cmds:
      - uv sync --locked --all-packages

  install-pre-commit:
    desc: "Setup pre-commit hooks"
    internal: true
    cmds:
      - uv run pre-commit install
