# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  sync:
    desc: "Sync local dev environment with repo state"
    cmds:
      - task: install-commitlint
      - task: install-python-deps
      - task: install-pre-commit-hook

  install-commitlint:
    desc: "Install commitlint"
    internal: true
    cmds:
      - npm clean-install --save-dev @commitlint/cli @commitlint/config-conventional

  install-python-deps:
    desc: "Install Python dependencies"
    internal: true
    cmds:
      - uv sync --locked --all-packages

  install-pre-commit-hook:
    desc: "Install pre-commit git hook"
    internal: true
    cmds:
      - uv run pre-commit install
