apiVersion: ENC[AES256_GCM,data:SR0=,iv:3Z+OPCk6wTAiFg2ufZnXB05mSbU0FyVPW95X3DQN0LE=,tag:uT13C98rxZ5SLs9u7Umu3Q==,type:str]
kind: ENC[AES256_GCM,data:pdG/L8O0,iv:Mg+jkj8MXVXpenDxWm78LQCTAZ34cf1IcmWqHv7DioA=,tag:R/H7GLPbbgkyW9A9op8C7Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VWI6e5ckzlvsID73TkfP,iv:JtYdqK+63+u4z26curUrCj3IPlJ/dYwu9CWOoa6beHk=,tag:okKXsQsMAD34aJIivwDypQ==,type:str]
    namespace: ENC[AES256_GCM,data:9VKfDFdJkxFH,iv:t6o46yVakKChifhnILD/7fkP08xl3DJBTogOhZvPc7o=,tag:MYgnjz0yeOJkHPBXzTPKEg==,type:str]
type: ENC[AES256_GCM,data:gmFJHOrd,iv:jPnsuIhzEnCUbkmAEukCUCFrN7ayJY5WBkRVIspTsyE=,tag:D3XlhfzoU+rfgbU/2xrsxg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BBdT1MsaRRE=,iv:m9bkXP0j+2fC1CTgbTpzHFQRuL6JN93y6pMADucuD0M=,tag:wG6W0Ssqw9fwyGFCt04bjg==,type:str]
    password: ENC[AES256_GCM,data:ROGX,iv:Y/pbrlQE5uDsnUFAS2ShckAbnXX2oAX6Vf3aI7SaMAo=,tag:ZOjsia/k/yB5JZqFf50Hgw==,type:str]
sops:
    age:
        - recipient: age1t7azpszznty3rr4a2h6sheq0zp946ds7830a5lg9uwqrkls8rqfs4t9vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc3FPVENFY0JseUFtejUv
            Ty9EM2pNUHp4dVdJem1lQ0h2bXVWdTA2dmpZCjYxUXQwTHpaSDVDaTM0SlJwb1F4
            QUhweFpRcUdqZnYva2VvM04xYzVnOVUKLS0tIHVhZjRBWmZnOEo0M3IwSHJMWGJJ
            czA1YTlxdDNyOEtWdU1LRVNYZVM5NUUKPF1VZEgrbcDBN1eJhAeDKNlCRNKg5exE
            wPBngY5PjespY9BP8TvE5HO7ujWG0PqVKePoX9yZrg79WpTvDq1gcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:36:08Z"
    mac: ENC[AES256_GCM,data:QVfMYS9CCnqd8Kgz3ANxAGrBM4DYXwNSd4l7IMh6QMB3nTqp06m5i8/5mBavoVYc82RJ6cOZsSyOWg6M8vKrlg21yM8Fpb95qQRMyw3UMlUwIGiUnpsw99XYALXVLsaFU7MYRfyOWY69Y1EJRoaDRdFJUI+424YLSK7fbn5fjlI=,iv:0e+sZOLYOelMva9ZUro0fhECTca31dur8R+clVwuGok=,tag:XUiCyYNzVDSj0gsMQc3J+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
