# --8<-- [start:image]
image:
  tag: "476"
# --8<-- [end:image]

# --8<-- [start:server]
server:
  workers: 2
  config:
    authenticationType: "oauth2"
  autoscaling:
    enabled: false
  keda:
    enabled: true
    minReplicaCount: 2
    maxReplicaCount: 5
    pollingInterval: 15
    initialCooldownPeriod: 0 # default 0s
    cooldownPeriod: 300 # default 300s, only applies when scaling to 0
    fallback:
      failureThreshold: 3
      replicas: 2
      behavior: "static"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 0
            selectPolicy: Max
            policies:
              - type: Percent
                value: 100
                periodSeconds: 120
              - type: Pods
                value: 5
                periodSeconds: 60
          scaleDown:
            stabilizationWindowSeconds: 300
            selectPolicy: Min
            policies:
              - type: Percent
                value: 10
                periodSeconds: 60
    triggers:
      - type: metrics-api
        metadata:
          url: "https://trino.trino.svc.cluster.local:8443/metrics"
          format: "prometheus"
          valueLocation: trino_execution_name_QueryManager_RunningQueries
          targetValue: "1"
          authMode: "bearer"
          unsafeSsl: "true"
        authenticationRef:
          name: keda-metric-api-creds
    annotations: {}
# --8<-- [end:server]

# --8<-- [start:resource-groups]
resourceGroups:
  type: configmap
  # Resource groups file is mounted to /etc/trino/resource-groups/resource-groups.json
  resourceGroupsConfig: |-
      {
        "rootGroups": [
          {
            "name": "global",
            "hardConcurrencyLimit": 10,
            "maxQueued": 100,
            "schedulingPolicy": "fair",
            "jmxExport": true
          }
        ],
        "selectors": [
          {
            "group": "global"
          }
        ]
      }

# --8<-- [end:resource-groups]

# --8<-- [start:coordinator]
coordinator:
  jvm:
    maxHeapSize: "8G"
  livenessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  readinessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  additionalVolumes:
    - name: tls-certs
      secret:
        secretName: trino-tls-secret
  additionalVolumeMounts:
    - name: tls-certs
      mountPath: /etc/trino/tls
      readOnly: true
  additionalExposedPorts:
    https:
      servicePort: 8443
      name: https
      port: 8443
      protocol: TCP
  additionalJVMConfig:
    - --sun-misc-unsafe-memory-access=allow
  # additionalConfigFiles:
  #   http-event-listener.properties: |
  #     event-listener.name=http
  #     http-event-listener.log-created=true
  #     http-event-listener.log-completed=true
  #     http-event-listener.connect-ingest-uri=<your ingest URI>
  # access-control.properties: |
  #   access-control.name=file
  #   security.refresh-period=150s
  #   security.config-file=/etc/trino/access-control/rules.json
# --8<-- [end:coordinator]



# --8<-- [start:worker]
worker:
  jvm:
    maxHeapSize: "8G"
  livenessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  readinessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  additionalJVMConfig:
    - --sun-misc-unsafe-memory-access=allow
  # additionalConfigFiles:
  #   http-event-listener.properties: |
  #     event-listener.name=http
  #     http-event-listener.log-created=true
  #     http-event-listener.log-completed=true
  #     http-event-listener.connect-ingest-uri=<your ingest URI>
# --8<-- [end:worker]

# --8<-- [start:catalogs]
catalogs:
  faker: |
    connector.name=faker
    faker.null-probability=0.1
    faker.default-limit=1000
    faker.locale=en

# https://trino.io/docs/current/connector/iceberg.html#authorization
# https://trino.io/docs/current/object-storage/file-system-s3.html
# --8<-- [end:catalogs]
