apiVersion: v1
kind: Service
metadata:
  name: thanos-ruler
  namespace: thanos
spec:
  clusterIP: None                  # headless，才能有 SRV
  selector:
    app.kubernetes.io/name: thanos-ruler
  ports:
    - name: grpc                   # 名稱很重要（_grpc）
      port: 10901
      targetPort: 10901
