# 3) ThanosRuler：從 Thanos Query 取數、把告警打進本集群的 Alertmanager
apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  name: thanos-ruler
  namespace: thanos
spec:
  replicas: 2
  # 讓 Ruler 去哪裡查詢（PromQL）— 指向 Thanos Query 的 HTTP 端點
  # 若你有 Query Frontend，也可改成前端的 service/URL
  queryEndpoints:
    - http://thanos-query-frontend.thanos.svc.cluster.local:9090
  # 把告警投遞到本命名空間由 Operator 自動建立的 "alertmanager-operated" 服務
  # （Operator 會為每個 namespace 建立 alertmanager-operated，供內部發現）
  alertmanagersUrl:
    - http://alertmanager-operated.thanos.svc.cluster.local:9093
  # 選取要載入的 PrometheusRule（見下方第 4 塊）
  ruleSelector:
    matchLabels:
      example-rules: "true"
  ruleNamespaceSelector: {}
  evaluationInterval: 30s
  objectStorageConfig:
    key: thanos.yaml
    name: thanos-objectstorage
  securityContext:
    fsGroup: 0
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    seccompProfile:
      type: 'RuntimeDefault'
  storage:                           # 若要保留本地 WAL/blocks 可設 PVC
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  tracingConfig:
    name: thanos-ruler-tracing
    key: tracing.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-ruler-tracing
  namespace: thanos
type: Opaque
stringData:
  tracing.yaml: |
    type: OTLP
    config:
      endpoint: jaeger-inmemory-instance-collector.jaeger.svc.cluster.local:4317
      service_name: thanos-ruler
      client_type: grpc
      sampler_type: ratelimiting
      sampler_param: 100
      insecure: true
      timeout: 10s
      retry_config:
        retry_enabled: true
        retry_initial_interval: 1s
        retry_max_interval: 5s
        retry_max_elapsed_time: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-ruler
  namespace: thanos
spec:
  clusterIP: None                  # headless，才能有 SRV
  selector:
    app.kubernetes.io/name: thanos-ruler
  ports:
    - name: grpc                   # 名稱很重要（_grpc）
      port: 10901
      targetPort: 10901
---
# 4) 範例 PrometheusRule（測試管線）：每 1m 觸發一個示範告警
# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: example-rules
#   namespace: thanos
#   labels:
#     example-rules: "true"
# spec:
#   groups:
#     - name: example
#       interval: 30s
#       rules:
#         - alert: ExampleAlwaysFiring
#           expr: vector(1)
#           for: 1m
#           labels:
#             severity: warning
#             namespace: thanos
#           annotations:
#             summary: "This is a demo alert to validate Ruler → Alertmanager path"
#             description: "If you see this in Alertmanager, the pipeline works."
