apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
    app.kubernetes.io/version: v0.39.2
  name: thanos-store
  namespace: thanos
spec:
  endpoints:
    - port: http
      relabelings:
        - action: replace
          separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
        - action: replace
          regex: shard\-(\d+)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_service_label_store_thanos_io_shard
          targetLabel: shard
  selector:
    matchLabels:
      app.kubernetes.io/component: object-store-gateway
      app.kubernetes.io/name: thanos-store
