apiVersion: ENC[AES256_GCM,data:nUk=,iv:3nTBouynbQgrPlO0CvLGNSc1cq6bBf03vLWu6frnKL8=,tag:2fThJ/+4L3+Idxssb/L/vQ==,type:str]
kind: ENC[AES256_GCM,data:p595o8JW,iv:m74JEWNFBLY+QDhCPRDMnPnhfMb0Bmf/sWlcz+6VDqQ=,tag:WKqyJ9DX8UcqXseM3WBZ7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0NiODpLI15oziuEr,iv:SqEuzBonGEnZSfoWuqCboBeCiqrOhF9d3wOhuKRrumM=,tag:ddsyQr3Cr8Mi6642m09C6Q==,type:str]
    namespace: ENC[AES256_GCM,data:1/cYf0GOTdI7,iv:Fi9kOJgsXwPhjXkV/PuIBl6WU08GyC+hCQD2i8ovBvk=,tag:jNYWfsFv0uWs3y2w0pVcvw==,type:str]
type: ENC[AES256_GCM,data:B9Vcvn/X,iv:WwRE8LRIHKM2cYvWjMl6WECb/CaO8B5WNXaMMLvE5Ig=,tag:nhD2rqvEBSfIYmxe+jqFew==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:bloYihk8bu4=,iv:iq/pbJ/1Bi8hGjtVYTrnHNGUYuA61WAJVkiXZgSU0k8=,tag:km4hgo5dcDEfJB9e8SN9ug==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:SLVD9rc+9X6R,iv:f0UQyUEh7OkVMH1aVOelU/+QBGis4NnBO2I8VM1SeXo=,tag:v6QY5g/TQs525w2d/C+HTg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:GVfNIxsqoA==,iv:Wi5eZPKaM6Py7a/+PTzNGOVDEBdekey99bUURUwWRfg=,tag:mhRReqc7airO2f0/TbOJ0A==,type:str]
sops:
    age:
        - recipient: age1t7azpszznty3rr4a2h6sheq0zp946ds7830a5lg9uwqrkls8rqfs4t9vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS0RUTHhkTW85cmRwU2ds
            N202SE9jWVpTMU1jNHNXeVhoVEx2dEEyZG5VClNXM0tZaXZCWDZpTzlBTVRlMjVC
            VkNOZVBuOFB1N2tXSzJLbU04bmdxSXMKLS0tIENNVXlZREZwRUk1cG91NjRIY1c3
            VzJxM1QxdjFCamRnWDh5RXEwMnQ4TFEKKuMgETk/UeiiX/keGaFHi3xM1rDeL5De
            7nw1tI30z+2aAPcfL3h/S91qYMRaPK12XujfrTzx8jzMdDl1nA9S7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:47:08Z"
    mac: ENC[AES256_GCM,data:og3uCYDN5hseKhbj+rgA+8/WO3YOs7qVGDdWP4sekvc+/gpS/gpkCX8bmuG/0W1WQbUyQNb30WVFDij2wOqA2dyVQZrIaB+oJYo/HigbsUWxZMzonh7hBs5Ev3TCCko9QvMOmZnfav499tDXXcLfOksNsW5jEjAxlLoF9K153BU=,iv:vWS9gPRQZKk5NyTAQrcAqe/wtv3XITCNoT9+xX3Xaq8=,tag:qvLEiM0+QHSQBlV01A1pyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
