apiVersion: v2
name: polaris-wrapper
description: Wrapper chart for Apache Polaris Iceberg REST catalog
type: application
version: 0.1.0
dependencies:
  - name: polaris
    version: 1.5.0
    repository: https://downloads.apache.org/polaris/helm-chart
