apiVersion: ENC[AES256_GCM,data:itk=,iv:h43AtQCuOKxiXfsBn5uV/FFhgeTqViO9h6qGE78UhTQ=,tag:eXB07+hKp5OwN0ztBBEWsw==,type:str]
kind: ENC[AES256_GCM,data:tcwhFJ8L,iv:w4fHhWCMwfpZFvwxtoF1MH+29Wn7hT3DEka08pm20bI=,tag:oLt/85tgUxr0W+WvmNexbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TBJfX5YaL/BPpPWPsMpx+Iio94D+lQ==,iv:46K7w0srlJ7knBo30qgzRqv0q5PYP0ahu4ae/qjovww=,tag:DTGckr0C+ok8K1YWlZmCkA==,type:str]
    namespace: ENC[AES256_GCM,data:MCdpLZ6ahQ==,iv:ivNGLKD9UIDzF2YA66YU9HT4Zk25QjLjtjn4R+nIThk=,tag:hXbugPC8G7jhum5cI8Woiw==,type:str]
type: ENC[AES256_GCM,data:OhzBI4fI,iv:1LjYuS4Q/wJGEfuAMcfiBRwuJa+jpR16nEMGnzhPdbU=,tag:jfOFIueMLNiLYo9tMnCDHw==,type:str]
stringData:
    awsAccessKeyId: ENC[AES256_GCM,data:958/l/CVqr1h1Q==,iv:Y3V8y8TV8VT+VrssmH3hc49pEUrqwHCvzhY0PwuUYLA=,tag:87xqzQ+Ck4mWZrSYDPKnRw==,type:str]
    awsSecretAccessKey: ENC[AES256_GCM,data:/qyeDfFn0tJjfg7yueM=,iv:/mYCR4V4PzR2jbX11TTR0a5awOH66+HDJZF+CxBb/y8=,tag:PW7TraMMtB6C+F2zD84btQ==,type:str]
sops:
    age:
        - recipient: age1t7azpszznty3rr4a2h6sheq0zp946ds7830a5lg9uwqrkls8rqfs4t9vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZGpjUnU2QzFlcDBxUHYr
            WmFXL21pS2gvbnlJOStiKzh1dHQyUlNIMVhzCnNHbi9CYzIvcWVZMTI0cGRSVU50
            V05pQWdGSjg4eU9QaXFSd2s4aFlIREkKLS0tIFQ5RXBmb1AzWHFzNTFSdk5kaWJs
            ZlBtbzNOR0JpSlJGay9HemR4enc5WjgKwawcAPLZYp+tzPHbOlqyKUEBuBpQAgw2
            pfd9c4/NX1zF78/hxze5fbzCrnWQRku8epZl4HGlH1XaAaXnb5/EyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:08:40Z"
    mac: ENC[AES256_GCM,data:W6Xsff4nA0wrlnDDoHEe5No41mEqKcIvspR0/aB1czBWTs9wzzXBIMps3pt3Xth3zAm1DjA+vvnXCHpD2Q6Mg+dM5OiUxL72CwQrO312c4Lv1PidyAj1nYc61TZVvFyEM4Syyvu2ywGc/qdihq4LCEMPVFZj7r1hg9Qnq0aY/kk=,iv:zahDozvwhAwIHaS5yAVqfDQlVXmBU9MyyNbREmyJVHM=,tag:5LNdwgfKW9cLzvCbSibKpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
