apiVersion: ENC[AES256_GCM,data:n4Q=,iv:taBtkVtoqhuMT3nbPQtZn7H5OAzjkfvvlxf5yCNeOxU=,tag:MbkEMjAnDzAq9+an8bfQjA==,type:str]
kind: ENC[AES256_GCM,data:e3jw9WmC,iv:3aREMgTa8MQnUychie0rLYUyUrBLqOcBXpmSmko2oZA=,tag:TGfHiUYxtqgrwltEPxVcHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NrgHIS+lD9KDAggy,iv:WJj+A5nvnjkMfzLnvshTbU4Ug6ZNPySO0JZIHuclkpk=,tag:3IhP9SRu+3pWS6jgsnT2/Q==,type:str]
    namespace: ENC[AES256_GCM,data:SGyxShI=,iv:+t1xS3HrGFJVL3DVzLqcmrL0SUWnSdHEB6bvxWN/6qU=,tag:sYvUk11LjwHPO7nLZdlO4A==,type:str]
type: ENC[AES256_GCM,data:IVn8LYJC,iv:0Lhqwpcjte8utx0qQvnW0gPOykZNeedVFdEKzb6nydM=,tag:O+AmZNGOQBxHwJ7DPvETlQ==,type:str]
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:7VliW1WyWiOUbg==,iv:+dYyqwSGs54hhkRL5j03Ba0NsOR2c3Gu6uf8saTYm5I=,tag:h8RzBKhb/hbdXvLQMuC70w==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:33mLBLEK7MNnA4TBXb8=,iv:XlFxpZgttJrRzD+TRBfjTj0mpR3x2M/sGwSNbl3/1Ws=,tag:C00N4gg5i5+1qy7nhYUwUA==,type:str]
sops:
    age:
        - recipient: age1t7azpszznty3rr4a2h6sheq0zp946ds7830a5lg9uwqrkls8rqfs4t9vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RUhaUHdwNHQ5NVppRE03
            UEo3ODBvMkpBNW9Zdit3ZU11cWlnRUVYb2dzCnlTMFlySVFDS1F6bmpITUpIMHpC
            S0F1T2JPakk4em4zSC9GdmlRbEs3bjQKLS0tIHRWRmNNdWJ2VkJEcThDZ3FGUFI4
            L1pBMjIzaDVLRUh0Tzd1S0ZKWUN2WHMK5McO2NUih5/cfCz5BhwDQEuKHN6wJh2z
            674H9iuLKKFBSu5Sq1LzLW1nFq/tejIXo8mci5Qlg7uK0+bqNl8xXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:49:51Z"
    mac: ENC[AES256_GCM,data:UDwuGLdKcZUNkwGs3fQmq9r+RP6kJvf0JeJL92wYS9R2BtVpcDwm2tNIHriISKPBr2bWDLic0yEL1OIZ6NTa+jE+WalkzfmOcuxCeioS+HXuv+vRVohwiBZfD2OEt2Om3+OU6ItstBrNohM3bypt9mtOJ1V8gYK6UvY20AHjGe8=,iv:9sn6aCe43biEi3zt/tpsxUsRPfoXMoI+CwqQjjYGKQY=,tag:1u/d8lYEcbaO2DvGLj5Kgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
