# --8<-- [start:image]
image:
  tag: "476"
# --8<-- [end:image]

# --8<-- [start:server]
server:
  workers: 2
  config:
    authenticationType: "oauth2"
  coordinatorExtraConfig: |
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.https.keystore.path=/etc/trino/tls/trino-dev.pem
    http-server.authentication.oauth2.issuer=https://accounts.google.com
    http-server.authentication.oauth2.client-id=$OAUTH2_CLIENT_ID
    http-server.authentication.oauth2.client-secret=$OAUTH2_CLIENT_SECRET
    http-server.authentication.oauth2.principal-field=email
    http-server.authentication.oauth2.scopes=openid,email
    web-ui.authentication.type=oauth2
  #   distributed-sort=true
  #   query.max-history=50
  # workerExtraConfig: |
  #   discovery.uri=http://trino.trino.svc.cluster.local:8080
# --8<-- [end:server]

# --8<-- [start:coordinator]
coordinator:
  jvm:
    maxHeapSize: "8G"
  livenessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  readinessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  secretMounts:
    - name: trino-tls
      secretName: trino-tls-secret
      path: /etc/trino/tls
  additionalExposedPorts:
    https:
      servicePort: 8443
      name: https
      port: 8443
      protocol: TCP
  additionalJVMConfig:
    - --add-opens=java.base/java.nio=ALL-UNNAMED # https://trino.io/docs/current/connector/bigquery.html#arrow-serialization-support
    - --sun-misc-unsafe-memory-access=allow
  # access-control.properties: |
  #   access-control.name=file
  #   security.refresh-period=150s
  #   security.config-file=/etc/trino/access-control/rules.json
# --8<-- [end:coordinator]



# --8<-- [start:worker]
worker:
  jvm:
    maxHeapSize: "8G"
  livenessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  readinessProbe:
    initialDelaySeconds: 30
    failureThreshold: 20
  additionalJVMConfig:
    - --add-opens=java.base/java.nio=ALL-UNNAMED # https://trino.io/docs/current/connector/bigquery.html#arrow-serialization-support
    - --sun-misc-unsafe-memory-access=allow
# --8<-- [end:worker]

# --8<-- [start:catalogs]
catalogs:
  faker: |
    connector.name=faker
    faker.null-probability=0.1
    faker.default-limit=1000
    faker.locale=en
  tpch: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  bigquery: |
    connector.name=bigquery
    bigquery.project-id=$PROJECT_ID
    bigquery.credentials-file=/etc/trino/bigquery/trino-sa.json
  iceberg: |
    iceberg.catalog.type=glue
    iceberg.file-format=parquet
    iceberg.security=READ_ONLY
    hive.metastore.glue.region=ap-northeast-1
    hive.metastore.glue.default-warehouse-dir=$ICEBERG_S3_URL
    hive.metastore.glue.aws-access-key=$AWS_ACCESS_KEY
    hive.metastore.glue.aws-secret-key=$AWS_SECRET_KEY
    fs.native-s3.enabled=true
    s3.region=ap-northeast-1
    s3.aws-access-key=$AWS_ACCESS_KEY
    s3.aws-secret-key=$AWS_SECRET_KEY

# https://trino.io/docs/current/connector/iceberg.html#authorization
# https://trino.io/docs/current/object-storage/file-system-s3.html
# --8<-- [end:catalogs]



# --8<-- [start:additionalConfigProperties]
additionalConfigProperties:
  - internal-communication.shared-secret=$INTERNAL_SHARED_SECRET
# --8<-- [end:additionalConfigProperties]

# --8<-- [start:additionalExchangeManagerProperties]
additionalExchangeManagerProperties: []
# additionalExchangeManagerProperties -- [Exchange manager
# properties](https://trino.io/docs/current/admin/fault-tolerant-execution.html#exchange-manager).
# @raw
# Example:
# ```yaml
#  - exchange.s3.region=object-store-region
#  - exchange.s3.endpoint=your-object-store-endpoint
#  - exchange.s3.aws-access-key=your-access-key
#  - exchange.s3.aws-secret-key=your-secret-key
# ```
# --8<-- [end:additionalExchangeManagerProperties]

# --8<-- [start:secretMounts]
# Allows mounting additional Trino configuration files from Kubernetes secrets on all nodes.
secretMounts:
  - name: trino-bigquery
    secretName: trino-bigquery-secret
    path: /etc/trino/bigquery
# --8<-- [end:secretMounts]