apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: kafka-ui
data:
  config.yml: |
    kafka:
      clusters:
        - name: retail-lakehouse
          bootstrapServers: kafka-cluster-kafka-bootstrap.kafka-cdc.svc.cluster.local:9092
          kafkaConnect:
            - name: debezium-connect-cluster
              address: http://debezium-connect-cluster-connect-api.kafka-cdc.svc.cluster.local:8083
            - name: polaris-cdc-connect-cluster
              address: http://polaris-cdc-connect-cluster-connect-api.kafka-cdc.svc.cluster.local:8083
            - name: iceberg-connect-cluster
              address: http://iceberg-connect-cluster-connect-api.kafka-cdc.svc.cluster.local:8083
    auth:
      type: DISABLED
    management:
      health:
        kafka:
          enabled: true
