apiVersion: v1
kind: Service
metadata:
  name: table-maintenance-backend
  namespace: default
  labels:
    app: table-maintenance-backend
spec:
  selector:
    app: table-maintenance-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
