{{- if and (ge 20 (int .Values.deploy.waveFrom)) (le 20 (int .Values.deploy.waveTo)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-trino
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20" # after opentelemetry-operator (wave 11)
spec:
  project: {{ .Values.project.name }}
  sources:
    - repoURL: https://github.com/kuanchoulai10/retail-lakehouse
      path: 20-jaeger-trino
      targetRevision: main
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: trino
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
