{{- if and (ge 21 (int .Values.deploy.waveFrom)) (le 21 (int .Values.deploy.waveTo)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-debezium-mysql-connector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21" # after kafka-cluster and mysql (wave 20)
spec:
  project: {{ .Values.project.name }}
  sources:
    - repoURL: https://github.com/kuanchoulai10/retail-lakehouse
      path: 21-kafka-debezium-mysql-connector
      targetRevision: main
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: kafka-cdc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
