{{- if and (ge 23 (int .Values.deploy.waveFrom)) (le 23 (int .Values.deploy.waveTo)) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "23" # after connect clusters (wave 21-22)
spec:
  project: {{ .Values.project.name }}
  sources:
    - repoURL: https://github.com/kuanchoulai10/retail-lakehouse
      path: platform/23-kafka-ui
      targetRevision: main
  destination:
    name: {{ .Values.spec.destination.name }}
    namespace: kafka-ui
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{- end }}
