apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trino-client-${TRINO_USER}
  namespace: trino
spec:
  secretName: trino-client-${TRINO_USER}-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: trino-ca-issuer
    kind: Issuer
  commonName: ${TRINO_USER}
  subject:
    organizations:
      - Trino
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
    encoding: PKCS8
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: trino-keystore-password
        key: password
