apiVersion: ENC[AES256_GCM,data:nZE=,iv:/h9Epkfabb1KCD07lQJUvjNGpVJufP4IMpojV9KL3Os=,tag:Lj7gYe4sV2sYApNIe1P/bg==,type:str]
kind: ENC[AES256_GCM,data:cdnpM9Q1,iv:J1viF6rEte3NnFZ6WFLwvdus6UASuDxejwi6HbAxJLs=,tag:fIpsOcGYc6BNFGqzRjOPRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F4vhjDtj0Gyr19WiWTs=,iv:i5OUTrwzU6ZiLSCg/uNw3eLEmCbmaczia0IRO4ra7qM=,tag:KCvK/5G3U4tbnOUqwx6n2g==,type:str]
    namespace: ENC[AES256_GCM,data:coFmpbYK+ZRM,iv:zlSxZ/eyi8sB/8gy6ESLct+UhYfb33BR0/YwfVjk1nA=,tag:6bV7r7vfcz0lwmc6VMJbtA==,type:str]
type: ENC[AES256_GCM,data:JqnycIEP,iv:V/dOMFTwVCNMo9ugzAFxPUVJBoLQ8NVovJS9VzDEy0o=,tag:/rArb4TAqtOhtveLZHKqrw==,type:str]
stringData:
    awsAccessKey: ENC[AES256_GCM,data:myt+Csw0I2U3ow==,iv:V9ntTVt8bRd27u374N/b7Z+0nM7GBWZih7O35g/NKZc=,tag:LSVlMvYHE1e2TulugvD8aw==,type:str]
    awsSecretAccessKey: ENC[AES256_GCM,data:uWH/sd09mWbj6U/FASI=,iv:7hePZao00XZthRWKHziuOVHmTT40amVjCGB4HhngETA=,tag:8HkPU/eUwUEacAuQCt0akQ==,type:str]
sops:
    age:
        - recipient: age1t7azpszznty3rr4a2h6sheq0zp946ds7830a5lg9uwqrkls8rqfs4t9vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORWp6a0s1NElEMWNmNnpr
            NlRLaE91dk1yVkQ3QmF1akJUekp1SFJETjFBClgzTFV2K0hJMFlFVFVPd2R1clpP
            dEMyMVZGeVVNbXpQV09ra1JpRVNkdXMKLS0tIGFhVjcrQ1hoTkFtYXJRaUkxbExx
            TXREZTErdThzWTR3Q1FTdytvT2FaODgKsRIlGKeK7eXPR4eCEoOXuodobp3X576w
            Sgw6sMelTRN+ZDAFsDGe7pbAuYoYI3zj0kN+s+ttjwwhm4ASVm8Mcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:04:48Z"
    mac: ENC[AES256_GCM,data:+RcBGFCX3sTEsm7c1+2z5aoOI90AeACRLrgw/gIWHjsZFb4ryHKSllByq4+/6ybERlgYT9AnVzeE7Q6Awwg8OPCDZXqxF9rXoZJfnkGwg/O27cu+jr7mmcjb6oJajIQ0cjoFyWLqA1Xfn4179BZGN+ibyYZ1jfq9LWP7fjtoX1g=,iv:iMG/9iCEoGxJIIukW2ppD7fudd/qmr9LncJpSkbemfI=,tag:bXwKvGONQnaw5z2f6TnyRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
